gitplugins:
  duplication:
    enabled: true
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 35
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 7
exclude_patterns:
  - "node_modules/"
  - "src/test/"
  - "dist/"
  - "coverage"